name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      logLevel:
        
      tags:
        description: 'Test scenario tags'
        required: true
        type: string
      

jobs:
  print-tag:
    runs-on: ubuntu-latest
    if:  ${{ inputs.print_tags }} 
    steps:
      - name: Print the input tag to STDOUT
        run: echo  The tags are ${{ inputs.tags }} 
